# Generated by Django 2.2.12 on 2022-08-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BinOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.IntegerField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binApp.Bin')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binApp.Operation')),
            ],
        ),
    ]
