# Generated by Django 2.2.12 on 2022-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binoperation',
            name='last_collection',
            field=models.DateTimeField(),
        ),
    ]
